### ISSUE TITLE
Unable to Connect to in VSCode After Connecting Google Drive and Authorizing GitHub

### ISSUE THREAD

**Issue by jijivski** [amitness/colab-connect#6]
I used this last week and it was perfect. However, after connecting Google Drive and authorizing GitHub, I am facing an issue with connecting to the remote extension host in VSCode. Although I can see the "Online" status in VSCode tunnels, I am unable to log in. I have tried reconnecting several times and even used another local computer, but the problem persists.

The error message I receive is:
"Failed to connect to the remote extension host server (Error: connection closed)"

Any suggestions or insights on how to resolve this issue would be greatly appreciated.

**Comment by jijivski** [comment]
I tried again today and worked. But not knowing why, any methods to diagnose when I face this again are appreciated.  
:D

**Comment by uho-33** [comment]
I encountered the same issue -- I couldn't connect to colab through vscode after it printed the following message:

```
Starting the tunnel  
- Ready!  
- Open VSCode on your laptop and open the command prompt  
- Select: 'Remote-Tunnels: Connect to Tunnel' to connect to Colab  
Logs:
```

After "Logs", nothing else was printed. I suspect this happened because the tunnel only supports a single client connection to the same remote instance at a time. There might have been another client already connected. However, even after closing all vscode windows, the issue persisted.

Ultimately, I solved the problem by renaming the tunnel. You can try my modified package in colab using the following code:

```python
!pip install -U git+https://github.com/uho-33/colab-connect.git  
from google.colab import drive  
drive.mount('/content/drive')  

from colabconnect import colabconnect  
colabconnect("test")    # Use "test" as the new tunnel name  
```
